version: "3.8"
services:
  tcpdump:
     image: kaazing/tcpdump
     network_mode: "host"
     volumes:
       - ./tcpdump:/tcpdump
  router:
    container_name: router
    build: .
    ports:
      - "51510/udp"
    command: ["router"]
    tty: true 
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - ALL
  reciever:
    container_name: endpoint
    build: .
    ports:
      - "51510/udp"
    command: ["element", "--recieve"]
    tty: true 
    stdin_open: true
    cap_add:
      - ALL
  sender:
    container_name: sender
    build: .
    ports:
      - "51510/udp"
    command: ["element", "--send"]
    tty: true
    stdin_open: true
    cap_add:
      - ALL
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16