---
version: "2.1"
services:
  broker:
    container_name: broker
    cap_add:
      - NET_ADMIN
      - ALL
    build:
      context: .
      dockerfile: "Dockerfile.broker"
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /config
    ports:
      - "3000"
      - "50001/udp"
    command: [ "broker", "--port", "50001"]
    restart: unless-stopped
  sub:
    container_name: sub
    build: .
    cap_add:
      - ALL
    stdin_open: true
    tty: true 
    ports:
      - "50001/udp"
    command: [ "sub", "--port", "50001"]
    depends_on: 
      - "broker"
  pub:
    container_name: pub
    cap_add:
      - ALL
    build: .
    ports:
      - "50001/udp"
    command: [ "pub", "--port", "50001"]
    depends_on: 
      - "sub"