---
version: "2.1"
services:
  tcpdump:
     image: kaazing/tcpdump
     network_mode: "host"
     volumes:
       - ./tcpdump:/tcpdump
  broker:
    container_name: broker
    cap_add:
      - NET_ADMIN
      - ALL
    build: .
    ports:
      - "3000"
      - "50001/udp"
    command: [ "broker", "--port", "50001"]
    restart: unless-stopped
  sub:
    container_name: sub
    build: .
    cap_add:
      - ALL
    stdin_open: true
    tty: true 
    ports:
      - "50001/udp"
    command: [ "sub", "--port", "50001"]
  sub2: 
    container_name: sub2
    build: .
    cap_add: 
      - ALL
    stdin_open: true
    tty: true 
    ports:
      - "50001/udp"
    command: [ "sub", "--port", "50001"]
  pub:
    container_name: pub
    cap_add:
      - ALL
    build: .
    ports:
      - "50001/udp"
    command: [ "pub", "--port", "50001"]
  pub2:
    container_name: pub2
    cap_add:
      - ALL
    build: .
    ports:
      - "50001/udp"
    command: [ "pub", "--port", "50001"]
    