---
version: "2.1"
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /config
    
    expose:
      - "3000"
      - "50001/udp"
    restart: unless-stopped
  broker:
    container_name: broker
    build: .
    ports:
      - "50001/udp"
    command: [ "broker", "--port", "50001"]
    depends_on: 
      - "wireshark"
  sub:
    container_name: sub
    build: .
    ports:
      - "50001/udp"
    command: [ "sub", "--port", "50001", "--brokerip", "172.0.0.2"]
    depends_on: 
      - "broker"
  pub:
    container_name: pub
    build: .
    ports:
      - "50001/udp"
    command: [ "pub", "--port", "50001", "--brokerip", "172.0.0.2"]
    depends_on: 
      - "sub"